{{- if .Values.ingress.enabled -}}
{{- $fullName := include "docker-registry-browser.fullname" . -}}
{{- $svcPort := .Values.service.port -}}
# {{- $serviceName := include "docker-registry-browser.fullname" . -}}
{{- $servicePort := .Values.service.port -}}
{{- $path := .Values.ingress.path -}}
# {{- if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
# apiVersion: networking.k8s.io/v1beta1
# {{- else -}}
# apiVersion: extensions/v1beta1
# {{- end }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    # {{- include "docker-registry-browser.labels" . | nindent 4 }}
{{- if .Values.ingress.labels }}
{{ toYaml .Values.ingress.labels | indent 4 }}
{{- end }}
  annotations:
    {{- range $key, $value := .Values.ingress.annotations }}
      {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  rules:
    {{- range $host := .Values.ingress.hosts }}
    - host: {{ $host }}
      http:
        paths:
          - path: {{ $path }}
            pathType: Prefix
            backend:
              service:
                name: {{ $fullName }}
                port: 
                  number: {{ $servicePort }}
    {{- end -}}
  {{- if .Values.ingress.tls }}
  tls:
{{ toYaml .Values.ingress.tls | indent 4 }}
  {{- end -}}
{{- end }}
